# Generated by Django 4.1.3 on 2022-11-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocator', '0002_imagesdb_location_alter_imagesdb_image_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesdb',
            name='image_lat_long',
            field=models.TextField(default='LatLng(0, 0)'),
        ),
        migrations.AlterField(
            model_name='imagesdb',
            name='image_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='imagesdb',
            name='image_long',
            field=models.FloatField(default=0),
        ),
    ]
